Important recommended books for nachine learning an data science tools

Introduction to Machine Learning with Python by Andreas Mueller and Sarah Guido (O’Reilly)

Python Data Science Handbook by Jake VanderPlas (O’Reilly)

Data Science from Scratch: First Principles with Python by Joel Grus (O’Reilly)

Python Machine Learning by Sebastian Raschka (Packt Publishing)

Hands-On Machine Learning with Scikit-Learn and TensorFlow by Aurélien Géron (O’Reilly)

In [1]:
import pandas as pd
import numpy as np

In [2]:
fruits = ["apple",'orange','apple','apple']*2
N = len(fruits)

df = pd.DataFrame({'fruit': fruits,   
                   'basket_id': np.arange(N),   
                  'count': np.random.randint(3, 15, size=N),   
                   'weight': np.random.uniform(0, 4, size=N)},   
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df


basket_id   fruit  count    weight
0          0   apple      4  3.400819
1          1  orange     13  2.190462
2          2   apple      8  3.425592
3          3   apple     12  3.488292
4          4   apple     13  2.842282
5          5  orange     14  1.866985
6          6   apple      7  0.605304
7          7   apple      6  2.702127

In [3]:
fruit_cat = df['fruit'].astype('category')
fruit_cat.values.categories

Index(['apple', 'orange'], dtype='object')

In [4]:
cat = pd.Categorical(['male','female','male','female','male','male','male'])
cat = ['male','female']
code = [1,0,1,0,1,1,1]
my_cats_2 = pd.Categorical.from_codes(code, cat,ordered=True)
my_cats_2

['female', 'male', 'female', 'male', 'female', 'female', 'female']
Categories (2, object): ['male' < 'female']

In [5]:
my_cats_2.as_ordered()

['female', 'male', 'female', 'male', 'female', 'female', 'female']
Categories (2, object): ['male' < 'female']

In [6]:
np.random.seed(1234)

draws = np.random.rand(1000)
draws[:5]

bins = pd.qcut(draws,4,labels = ['Q1','Q2','Q3','Q4'])
bins


['Q1', 'Q3', 'Q2', 'Q4', 'Q4', ..., 'Q4', 'Q4', 'Q1', 'Q2', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [7]:
bins.codes[:10]

array([0, 2, 1, 3, 3, 1, 1, 3, 3, 3], dtype=int8)

In [10]:
df = pd.DataFrame({
    'key':['a','b','c']*4,
    'values':np.arange(12.)
})
df

key  values
0    a     0.0
1    b     1.0
2    c     2.0
3    a     3.0
4    b     4.0
5    c     5.0
6    a     6.0
7    b     7.0
8    c     8.0
9    a     9.0
10   b    10.0
11   c    11.0

In [17]:
gr = df.groupby('key').values
grouped = gr.transform(lambda x: x.mean())
grouped
gr.transform(lambda x: (x-x.mean())/x.std())

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: values, dtype: float64

In [23]:
times = pd.date_range('1-8-2021 16:40:00',periods=15,freq="1min")
times[:3]

DatetimeIndex(['2021-01-08 16:40:00', '2021-01-08 16:41:00',
               '2021-01-08 16:42:00'],
              dtype='datetime64[ns]', freq='T')

In [27]:
df2 = pd.DataFrame({
    "time":times,
    "value":np.arange(15)
})
df2[:3]

time  value
0 2021-01-08 16:40:00      0
1 2021-01-08 16:41:00      1
2 2021-01-08 16:42:00      2

In [30]:
df2.set_index("time").resample("5min").count()
df2

time  value
0  2021-01-08 16:40:00      0
1  2021-01-08 16:41:00      1
2  2021-01-08 16:42:00      2
3  2021-01-08 16:43:00      3
4  2021-01-08 16:44:00      4
5  2021-01-08 16:45:00      5
6  2021-01-08 16:46:00      6
7  2021-01-08 16:47:00      7
8  2021-01-08 16:48:00      8
9  2021-01-08 16:49:00      9
10 2021-01-08 16:50:00     10
11 2021-01-08 16:51:00     11
12 2021-01-08 16:52:00     12
13 2021-01-08 16:53:00     13
14 2021-01-08 16:54:00     14

In [35]:
N =15
df2 = pd.DataFrame({'time': times.repeat(3),
                     'key': np.tile(['a', 'b', 'c'], N),
                        'value': np.arange(N * 3.)})
df2[:4]

time key  value
0 2021-01-08 16:40:00   a    0.0
1 2021-01-08 16:40:00   b    1.0
2 2021-01-08 16:40:00   c    2.0
3 2021-01-08 16:41:00   a    3.0

In [54]:
time_key = pd.Grouper('1min')
# time_gr.mean
resampled = (df2.set_index('time').groupby(['key',time_key]).sum()
)

# TimeGrouper is depreciated in current verion 

KeyError: 'The grouper name 1min is not found'

In [3]:
from pandas import load_data
df = load_data()
df2 = df[df['col2'] < 0]
df2['col1_demeaned'] = df2['col1'] - df2['col1'].mean()
result = df2.groupby('key').col1_demeaned.std()

ImportError: cannot import name 'load_data' from 'pandas' (c:\users\gaurav sahu\python-new-install\lib\site-packages\pandas\__init__.py)

In [26]:
df1['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                      categories=['a', 'b'])

df1['category']=pd.Categorical(['a','b','a','b','a'],categories=['a','b'])
dum = pd.get_dummies(df1.category,prefix='category')
df1=df1.drop('category',axis=1).join(dum)


In [31]:
df1
data = pd.DataFrame({
        'x0': [1, 2, 3, 4, 5],
        'x1': [0.01, -0.01, 0.25, -4.1, 0.],
        'y': [-1.5, 0., 3.6, 1.3, -2.]})

In [35]:
import patsy 
y,X=patsy.dmatrices('y~x0+x1',data)
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [38]:
X
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [47]:
np.asarray(X)

df2 = patsy.dmatrices('y~x0+x1+0',data)[1]
df2

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [53]:
coef,rec,_,_=np.linalg.lstsq(X,y,rcond=None)
coef.shape
rec.shape

(1,)

In [65]:
coef.squeeze()
# coef
data1 = pd.Series(coef.squeeze(),index=X.design_info.column_names)
data1.index
X.design_info.column_names



['Intercept', 'x0', 'x1']

In [75]:
# y,X = patsy('y ~ x0 + np.log(np.abs(x1)+1)',data)
np.log(np.abs(data.x1)+1)
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [86]:
X
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)
data
new_data = pd.DataFrame({
    'x0':np.random.rand(7),
    'x1':np.random.randn(7),
    'y':np.arange(7)
})
patsy.build_design_matrices([X.design_info],new_data)

[DesignMatrix with shape (7, 3)
   Intercept  standardize(x0)  center(x1)
           1         -1.43077    -0.90332
           1         -1.63633     0.66941
           1         -2.03793    -1.03436
           1         -2.04373     0.37181
           1         -1.83076     1.48751
           1         -1.90285     2.30976
           1         -2.11854     0.13928
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [89]:
patsy.dmatrices('y~I(x0+x1)',data)

(DesignMatrix with shape (5, 1)
      y
   -1.5
    0.0
    3.6
    1.3
   -2.0
   Terms:
     'y' (column 0),
 DesignMatrix with shape (5, 2)
   Intercept  I(x0 + x1)
           1        1.01
           1        1.99
           1        3.25
           1       -0.10
           1        5.00
   Terms:
     'Intercept' (column 0)
     'I(x0 + x1)' (column 1))

In [118]:
data = pd.DataFrame({
   ....:     'key1': ['a', 'a', 'b', 'b', 'b', 'b', 'a', 'b'],
   ....:     'key2': [0, 1, 0, 1, 0, 1, 0, 0],
   ....:     'v1': [1, 2, 3, 4, 5, 6, 7, 8],
   ....:     'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
   ....: })
data
y,X = patsy.dmatrices('v2~key1+0',data)
X.mean()
X.design_info.column_names

['key1[a]', 'key1[b]']

In [119]:
y1,X1 = patsy.dmatrices('v2~C(key1)',data)
X1
data['key2']=data['key2'].map({0:'Zero',1:'one'})
data

key1  key2  v1   v2
0    a  Zero   1 -1.0
1    a   one   2  0.0
2    b  Zero   3  2.5
3    b   one   4 -0.5
4    b  Zero   5  4.0
5    b   one   6 -1.2
6    a  Zero   7  0.2
7    b  Zero   8 -1.7

In [121]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)
X


DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.one]  key1[T.b]:key2[T.one]
          1          0            0                      0
          1          0            1                      0
          1          1            0                      0
          1          1            1                      1
          1          1            0                      0
          1          1            1                      1
          1          0            0                      0
          1          1            0                      0
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [146]:
# !pip install statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf

def dnorm(mean,variance,size=1):
    if isinstance(size,int):
        size=size
    return mean+np.sqrt(variance)*np.random.rand(size)
np.random.seed(1234)

N=100
X= np.c_[
    dnorm(0,0.2,size=N),
    dnorm(0,0.4,size=N),
    dnorm(0,0.6,size=N),
    dnorm(0,0.8,size=N)
]
X[:5].shape

eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

TypeError: RandomState.rand() argument after * must be an iterable, not int

In [151]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

# For reproducibility
np.random.seed(12345)

N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps
X[:5],y[:5]



(array([[-0.12946849, -1.21275292,  0.50422488],
        [ 0.30291036, -0.43574176, -0.25417986],
        [-0.32852189, -0.02530153,  0.13835097],
        [-0.35147471, -0.71960511, -0.25821463],
        [ 1.2432688 , -0.37379916, -0.52262905]]),
 array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109]))

In [176]:
X_model = sm.add_constant(X)

model = sm.OLS(y,X)
X_model[:4]
result = model.fit()
result.summary()  # amazing model summary 

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Mon, 11 Jan 2021   Prob (F-statistic):                    7.44e-12
Time:                        14:02:08   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1783      0.053      3.364      0.001       0.073       0.283
x2             0.2230      0.046      4.818      0.000       0.131       0.315
x3             0.5010      0.080      6.237      0.000       0.342       0.660
==============================================================================
Omnibus:                        4.662   Durbin-Watson:                   2.201
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                4.098
Skew:                           0.481   Prob(JB):                        0.129
Kurtosis:                       3.243   Cond. No.                         1.74
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [183]:
X_model.shape
frame = pd.DataFrame(X,columns=['one','two','three'])
frame['y']=y
frame[:10]

one       two     three         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941
5  0.881267 -0.028090 -0.368960 -0.045015
6  0.058760  0.848485 -1.182616  0.087577
7  0.178192  0.759824 -0.068417 -0.504568
8  0.486373 -0.456615 -0.336269 -0.545824
9  0.788315  1.225180 -0.059305  0.265271

In [204]:
results = smf.ols('y~one*two+three+0',data=frame).fit()
results.summary()
results .params

type(results)
results.tvalues,results.params

(one        3.170199
 two        4.795780
 one:two    0.345151
 three      6.194032
 dtype: float64,
 one        0.173755
 two        0.225396
 one:two    0.026698
 three      0.504985
 dtype: float64)

In [205]:
results.predict(frame[:5])


0   -0.037028
1   -0.177463
2    0.007302
3   -0.346909
4   -0.144557
dtype: float64

In [221]:
train = pd.read_csv("train.csv")
train.head(
)
test = pd.read_csv("test.csv")
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [222]:
# titanic.info()
# test.info()
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [229]:
value = train['Age'].median()
value
train["Age"] =train["Age"].fillna(value) 
test["Age"] = test["Age"].fillna(value)
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [246]:
train['IsFemale'] = (train['Sex']=='female').astype(int)

test['IsFemale'] = (test['Sex']=='female').astype(int)
train[:10]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male  28.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  IsFemale  
0      0         A/5 21171   7.2500   NaN        S         0  
1      0          PC 17599  71.2833   C85        C         1  
2      0  STON/O2. 3101282   7.9250   NaN        S         1  
3      0            113803  53.1000  C123        S         1  
4      0            373450   8.0500   NaN        S         0  
5      0            330877   8.4583   NaN        Q         0  
6      0             17463  51.8625   E46        S         0  
7      1            349909  21.0750   NaN        S         0  
8      2            347742  11.1333   NaN        S         1  
9      0            237736  30.0708   NaN        C         1

In [242]:
predictors  =['Pclass','IsFemale','Age']

X_train = train[predictors].values

X_test = test[predictors].values
y = train["Survived"].values
y[:10]
X_train[:10]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.],
       [ 3.,  0., 28.],
       [ 1.,  0., 54.],
       [ 3.,  0.,  2.],
       [ 3.,  1., 27.],
       [ 2.,  1., 14.]])

In [248]:
from sklearn.linear_model import LogisticRegression
line = LogisticRegression()
model = line.fit(X_train,y)
model


LogisticRegression()

In [252]:
prediction = model.predict(X_test)
prediction[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [255]:
from sklearn.linear_model import LogisticRegressionCV
line_cv = LogisticRegressionCV()
model_cv = line.fit(X_train,y)
model_cv

LogisticRegressionCV()

In [258]:
from sklearn.model_selection import cross_val_score

model = LogisticRegression(C=10)

scores = cross_val_score(model, X_train, y, cv=4)

scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])