In [1]:
import pandas as pd
import numpy as np


In [45]:
# np.int64.mro()
# np.issubdtype(1, np.number)
arr = np.arange(8)
fa= arr.reshape((4,2),order='F')

ca = arr.reshape((4,2),order='C')
fa.reshape((2,2,2))


array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [3]:
arr.ravel(order="C")   # not return copy of it 
arr.flatten(order="F")   # return copy of it

arr1 = np.arange(6).reshape((3,2))
arr2 = np.arange(6,0,-1).reshape((3,2))
c = np.concatenate([arr1,arr2],axis=1)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
np.split(c,[1,5])
arr1.repeat(2,axis=0)
arr1.repeat([2,1],axis=1)


array([[0, 0, 1],
       [2, 2, 3],
       [4, 4, 5]])

In [5]:
np.random.seed(1234)
arr = np.random.rand(2,2)
np.tile(arr,2),arr
ar = np.arange(10)*10
ar.take([1,2,4,9])
ar.put([1,2,3],[45,45,46])
ar

array([ 0, 45, 45, 46, 40, 50, 60, 70, 80, 90])

# THE BROADCASTING RULE
Two arrays are compatible for broadcasting if for each trailing dimension (i.e., starting from the end) the axis lengths match or if either of the lengths is 1. Broadcasting is then performed over the missing or length 1 dimensions.

In [6]:
arr = np.random.rand(5,3)
mu = arr.mean(1)
mu = mu.reshape(5,1)

(arr-mu).mean(1)



array([ 3.70074342e-17,  3.70074342e-17,  7.40148683e-17, -3.70074342e-17,
        5.55111512e-17])

In [7]:
arr = np.zeros((4, 4))

arr_3d = arr[:,np.newaxis,:]
arr_3d.shape
ar = np.random.normal(size=(3,4))
mu1 = ar.mean(axis=0)
mu1

array([-0.12013095,  0.57324425, -0.25441808,  0.6802219 ])

# Advanced ufunc usage

In [23]:
np.random.seed(1234)
arr = np.random.randn(5,4)

arr[::]

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03],
       [ 4.05453412e-01,  2.89091941e-01,  1.32115819e+00,
        -1.54690555e+00]])

In [34]:
arr[::2].sort(1)

t = arr[:,:-1]<arr[:,1:]
np.logical_and.reduce(t,axis=1)
t

array([[ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [46]:
arr = np.arange(12).reshape((3,4))
arr.all(0),np.logical_and.reduce(arr,axis=0)


(array([False,  True,  True,  True]), array([False,  True,  True,  True]))

In [65]:
ar = np.arange(10)
#  sum of till ar[0:1]  ,ar[1:4],   ar[4:]
n = np.add.reduceat(ar,[0,1,4])
ar,n


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  6, 39], dtype=int32))

In [83]:
def add_element(x,y):
    return x+y

add = np.frompyfunc(add_element,2,1)
a = add(np.arange(4),np.arange(4))

arr = np.random.randn(1000000)

# t1 = %timeit np.add(arr,arr)

t2 = %timeit add(arr,arr)
t2

3.37 ms ± 414 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
134 ms ± 3.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [95]:
dtype = [('x',np.int32),('y',np.float32)]

dtype = [('x',np.int32,3),('y',np.float32,2)]
a = np.ones(4,dtype=dtype)
a['x']

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [101]:
value = np.arange(10,0,-1)
value.argsort()

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [2]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['sahu', 'pintu', 'Steve', 'gates Bill','narendra modi'])
sorter = np.lexsort((first_name,last_name))
sorter
list(zip(first_name[sorter],last_name[sorter]))

[('Steve', 'Steve'),
 ('Bill', 'gates Bill'),
 ('Barbara', 'narendra modi'),
 ('Jane', 'pintu'),
 ('Bob', 'sahu')]

In [5]:
def mean_distance(x,y):
    lx = len(x)
    result=0.0
    count=0
    for i in range(lx):
        result+=x[i]-y[i]
        count+=1
    return result/count
a1 = np.arange(1000000)
a2 = np.arange(1000000)
# mean_distance(a1,a2)
%timeit mean_distance(a1,a2)


570 ms ± 21.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit (a1-a2).mean()

2.95 ms ± 53.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
# p = np.memmap("mymmap",dtype='float64',mode = 'w+',shape=(1000,1000))


In [42]:
# section = p[:5]
# section= np.random.rand(5,1000)
# section
# p.flush()
# p
# del p


In [57]:
# p = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
# p
a1.flags
arr_c = np.ones((1000,1000),order="C")
arr_f = np.zeros((1000,1000),order="F")
arr_c.flags
arr_f.flags
arr_f.copy("C").flags
ar


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False